### ISSUE TITLE
Tell a user if they will be overwriting votes for a different district in senate elections

### ISSUE THREAD

**Issue by stephenermshar** [ASWWU-Web/elections#61]
If a user votes for one district and then goes to vote for a different district their votes for the first district are removed, it would be good to indicate to the user whether they already have votes in another district that will be overwritten.

**Comment by kadensu** [comment]
We want users to be aware of their past votes so they know if they're overwriting votes, or so they're aware of who they have already voted for. This could be achieved by displaying current votes throughout the entire voting process. So for the general/ASWWU election, displaying what votes have been already cast. This could be done by listing the votes close to the top of the screen, or having a tab at the bottom of the screen that can be swiped up to view current votes.
